### ISSUE TITLE
panic: unexpected type: *xpath.attributeQuery

### ISSUE THREAD

**Issue by smacker** [bblfsh/sdk#357]
```go
package main

import (
	"fmt"

	bblfsh "gopkg.in/bblfsh/client-go.v3"
	"gopkg.in/bblfsh/client-go.v3/tools"
)

var code = `package main
func myname() {}`

func main() {
	client, err := bblfsh.NewClient("0.0.0.0:9432")
	if err != nil {
		panic(err)
	}

	res, _, err := client.NewParseRequest().Language("go").Content(code).UAST()
	if err != nil {
		panic(err)
	}

	name, err := tools.FilterString(res, "string(//uast:FunctionGroup/*/uast:Alias/Name/@Name)")
	fmt.Println(name, err)
}
```

```
$ go run panic.go
panic: unexpected type: *xpath.attributeQuery

goroutine 1 [running]:
github.com/antchfx/xpath.asString(0x166eb60, 0xc0001ce340, 0x1569aa0, 0xc0001ce2c0, 0xc0001ce2c0, 0x0)
	/Users/smacker/go/src/github.com/antchfx/xpath/func.go:199 +0x1ef
github.com/antchfx/xpath.stringFunc(0x1671d20, 0xc0001ce2c0, 0x166eb60, 0xc0001ce340, 0xc000046c01, 0xc0001ce340)
	/Users/smacker/go/src/github.com/antchfx/xpath/func.go:218 +0x75
github.com/antchfx/xpath.(*functionQuery).Evaluate(0xc0001ce2e0, 0x166eb60, 0xc0001ce340, 0xc0001d0b70, 0xc0000cbc98)
	/Users/smacker/go/src/github.com/antchfx/xpath/query.go:563 +0x4f
github.com/antchfx/xpath.(*Expr).Evaluate(0xc0001ce300, 0x16775e0, 0xc0001ce320, 0x10, 0x1572c60)
	/Users/smacker/go/src/github.com/antchfx/xpath/xpath.go:120 +0x87
gopkg.in/bblfsh/sdk.v2/uast/query/xpath.(*xQuery).Execute(0xc0001d0b70, 0x1674060, 0xc0001d2090, 0x166e160, 0xc0001d0b70, 0x0, 0x0)
	/Users/smacker/go/src/gopkg.in/bblfsh/sdk.v2/uast/query/xpath/xpath.go:45 +0xd0
gopkg.in/bblfsh/sdk.v2/uast/query/xpath.(*index).Execute(0x1a68768, 0x1674060, 0xc0001d2090, 0x15ff116, 0x34, 0x102b761, 0x1677688, 0xc0000cbdf0, 0xc0001c62c0)
	/Users/smacker/go/src/gopkg.in/bblfsh/sdk.v2/uast/query/xpath/xpath.go:35 +0x9c
gopkg.in/bblfsh/client-go.v3/tools.(*Context).Filter(0xc0000cbec8, 0x15ff116, 0x34, 0x1676480, 0xc0001d2090, 0x0, 0x0)
	/Users/smacker/go/src/gopkg.in/bblfsh/client-go.v3/tools/context.go:29 +0xac
gopkg.in/bblfsh/client-go.v3/tools.(*Context).FilterNode(0xc0000cbec8, 0x15ff116, 0x34, 0xc0000cbe80, 0x100dc28, 0x0, 0x154bbc0)
	/Users/smacker/go/src/gopkg.in/bblfsh/client-go.v3/tools/context.go:34 +0x43
gopkg.in/bblfsh/client-go.v3/tools.(*Context).FilterString(0xc0000cbec8, 0x15ff116, 0x34, 0xc00009e008, 0x15f2636, 0x1d, 0xc000082080)
	/Users/smacker/go/src/gopkg.in/bblfsh/client-go.v3/tools/context.go:104 +0x43
gopkg.in/bblfsh/client-go.v3/tools.FilterString(0x1676480, 0xc0001d2090, 0x15ff116, 0x34, 0x2, 0x0, 0x0, 0x0)
	/Users/smacker/go/src/gopkg.in/bblfsh/client-go.v3/tools/context.go:147 +0x9a
main.main()
	/Users/smacker/Dev/anomaly/panic.go:24 +0x149
exit status 2
```

**Comment by juanjux** [comment]
Same as in #358 - doesn't crash here, but returns `nil` since the query doesn't seem to be correct.

**Comment by smacker** [comment]
true. looks like the bug was fixed in xpath lib but I had older version in my $GOPATH.
